export { ReactComponent as ArrowLeftIcon, default as arrowLeftSvg } from './arrow-left.svg';
export {
  ReactComponent as ArrowRightFromBracketIcon,
  default as arrowRightFromBracketSvg,
} from './arrow-right-from-bracket.svg';
export { ReactComponent as BankIcon, default as bankSvg } from './bank.svg';
export { ReactComponent as BarsIcon, default as barsSvg } from './bars.svg';
export { ReactComponent as BriefcaseIcon, default as briefcaseSvg } from './briefcase.svg';
export { ReactComponent as Building02Icon, default as building02Svg } from './building-02.svg';
export { ReactComponent as CalendarDaysIcon, default as calendarDaysSvg } from './calendar-days.svg';
export { ReactComponent as CalendarIcon, default as calendarSvg } from './calendar.svg';
export { ReactComponent as ChartColumnIcon, default as chartColumnSvg } from './chart-column.svg';
export { ReactComponent as ChartLineIcon, default as chartLineSvg } from './chart-line.svg';
export { ReactComponent as ChartPieIcon, default as chartPieSvg } from './chart-pie.svg';
export { ReactComponent as CheckIcon, default as checkSvg } from './check.svg';
export { ReactComponent as ChevronRightIcon, default as chevronRightSvg } from './chevron-right.svg';
export { ReactComponent as CircleInfoIcon, default as circleInfoSvg } from './circle-info.svg';
export { ReactComponent as CircleQuestionIcon, default as circleQuestionSvg } from './circle-question.svg';
export { ReactComponent as Coins02Icon, default as coins02Svg } from './coins-02.svg';
export { ReactComponent as CoinsHandIcon, default as coinsHandSvg } from './coins-hand.svg';
export { ReactComponent as CoinsStacked01Icon, default as coinsStacked01Svg } from './coins-stacked-01.svg';
export { ReactComponent as CoinsStacked03Icon, default as coinsStacked03Svg } from './coins-stacked-03.svg';
export { ReactComponent as CommentIcon, default as commentSvg } from './comment.svg';
export { ReactComponent as CreditCard01Icon, default as creditCard01Svg } from './credit-card-01.svg';
export { ReactComponent as Cryptocurrency01Icon, default as cryptocurrency01Svg } from './cryptocurrency-01.svg';
export { ReactComponent as DataFlow03Icon, default as dataFlow03Svg } from './dataflow-03.svg';
export { ReactComponent as FilterIcon, default as filterSvg } from './filter.svg';
export { ReactComponent as FolderIcon, default as folderSvg } from './folder.svg';
export { ReactComponent as GearIcon, default as gearSvg } from './gear.svg';
export { ReactComponent as Gift01Icon, default as gift01Svg } from './gift-01.svg';
export { ReactComponent as GiftIcon, default as giftSvg } from './gift.svg';
export { ReactComponent as LeftRightIcon, default as leftRightSvg } from './left-right.svg';
export { ReactComponent as Ling01Icon, default as ling01Svg } from './link-01.svg';
export { ReactComponent as LingBroken01Icon, default as lingBroken01Svg } from './link-broken-01.svg';
export { ReactComponent as LoadingIcon, default as loadingSvg } from './loading.svg';
export { ReactComponent as LogOut01Icon, default as logOut01Svg } from './log-out-01.svg';
export { ReactComponent as Logo, default as logoSvg } from './logo.svg';
export {
  ReactComponent as MessageQuestionSquareIcon,
  default as messageQuestionSquareSvg,
} from './message-question-square.svg';
export { ReactComponent as MinusIcon, default as minusSvg } from './minus.svg';
export { ReactComponent as MiscellaneousIcon, default as miscellaneousSvg } from './miscellaneous.svg';
export { ReactComponent as PlusCircleIcon, default as plusCircleSvg } from './plus-circle.svg';
export { ReactComponent as PlusIcon, default as plusSvg } from './plus.svg';
export { ReactComponent as PiggyBank01Icon, default as piggyBank01Svg } from './piggy-bank-01.svg';
export { ReactComponent as RefreshCW03Icon, default as refreshCW03Svg } from './refresh-cw-03.svg';
export { ReactComponent as ReverseRightIcon, default as reverseRightSvg } from './reverse-right.svg';
export { ReactComponent as RightLeftIcon, default as rightLeftSvg } from './right-left.svg';
export { ReactComponent as RightLongIcon, default as rightLongSvg } from './right-long.svg';
export { ReactComponent as SafeIcon, default as safeSvg } from './safe.svg';
export { ReactComponent as ScrewdriverWrenchIcon, default as screwdriverWrenchSvg } from './screwdriver-wrench.svg';
export { ReactComponent as SearchMdIcon, default as searchMdSvg } from './search-md.svg';
export { ReactComponent as Settings02Icon, default as settings02Svg } from './settings-02.svg';
export { ReactComponent as ShieldTickIcon, default as shieldTickSvg } from './shield-tick.svg';
export { ReactComponent as ShuffleIcon, default as shuffleSvg } from './shuffle.svg';
export { ReactComponent as SortDownIcon, default as sortDownSvg } from './sort-down.svg';
export { ReactComponent as SortIcon, default as sortSvg } from './sort.svg';
export { ReactComponent as SortUpIcon, default as sortUpSvg } from './sort-up.svg';
export { ReactComponent as SpacingWidth01Icon, default as spacingWidth01Svg } from './spacing-width-01.svg';
export { ReactComponent as SwitchHorizontal01Icon, default as switchHorizontal01Svg } from './switch-horizontal-01.svg';
export { ReactComponent as TableIcon, default as tableSvg } from './table.svg';
export { ReactComponent as Tag01Icon, default as tag01Svg } from './tag-01.svg';
export { ReactComponent as Trash01Icon, default as trash01Svg } from './trash-01.svg';
export { ReactComponent as TrashIcon, default as trashSvg } from './trash-can.svg';
export { ReactComponent as TrendUp01Icon, default as trendUp01Svg } from './trend-up-01.svg';
export { ReactComponent as User01Icon, default as user01Svg } from './user-01.svg';
export { ReactComponent as UserIcon, default as userSvg } from './user.svg';
export { ReactComponent as UsersIcon, default as usersSvg } from './users.svg';
export { ReactComponent as Wallet01Icon, default as wallet01Svg } from './wallet-01.svg';
export { ReactComponent as Wallet03Icon, default as wallet03Svg } from './wallet-03.svg';
export { ReactComponent as XmarkIcon, default as xmarkSvg } from './xmark.svg';
